var pizza1 = new pizza(40, 2, 0);
var pizza2 = new pizza(30, 3, 1);
var pizza3 = new pizza(50, 7, 4);
var pizza4 = new pizza(45, 8, 2);
var pizza5 = new pizza(27, 4, 3);
document.write(pizza1.print());
document.write("<br/>");
document.write("toppings: " + pizza1.isBasicPizza());
document.write("<br/>");
document.write("<br/>");
document.write(pizza2.print() + "");
document.write("<br/>");
document.write("toppings: " + pizza2.isBasicPizza());
document.write("<br/>");
document.write("<br/>");
document.write(pizza3.print() + "");
document.write("<br/>");
document.write("toppings: " + pizza3.isBasicPizza());
document.write("<br/>");
document.write("<br/>");
document.write(pizza4.print() + "");
document.write("<br/>");
document.write("toppings: " + pizza4.isBasicPizza());
document.write("<br/>");
document.write("<br/>");
document.write(pizza5.print() + "");
document.write("<br/>");
document.write("toppings: " + pizza5.isBasicPizza());
document.write("<br/>");
document.write("<br/>");
//# sourceMappingURL=app.js.map